spring.application.name=SpringEduManager

# Configuracion de Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:edudb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar Consola H2 para navegadores
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true